version: 2

sources:
  - name: raw
    database: raw  
    schema: movies  
    tables:
      - name: netflix_titles
      - name: meta_critic

models:
  - name: netflix_titles
    description: "tabela de filmes"
    columns:
      - name: show_id
        tests:
          - unique
          - not_null
